### ISSUE TITLE
VM Start/stop Issue

### ISSUE THREAD

**Issue by indumathymk** [Azure-Samples/virtual-machines-python-manage#27]
Am using following API to start automatically in scheduler,
 compute_client.virtual_machines.start(group,vmName)
async_vm_start.wait() 

Most of the time auto start not working will take a long time to start.

I comment that **async_vm_start.wait()**  and tried,was given fast response.

Need to know why this function used during VM Start?

**Comment by lmazuel** [comment]
Hi @indumathymk 
If you don't need to wait for this to start, you can pass polling=False as parameter, that will exist immediately. If you really need to be sure it started, you have to wait....
Note that the best place to discuss this matter is inside the main repo:
https://github.com/Azure/azure-sdk-for-python
